# Generated by Django 6.1.1 on 2026-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subscription_until',
            field=models.DateField(blank=True, help_text='Пусто = бессрочная подписка. Дата в прошлом = доступ закрыт.', null=True, verbose_name='Подписка активна до'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Если включено — студенты не увидят информацию группы', verbose_name='Закрыть доступ вручную'),
        ),
    ]
